<h2>Hinweise</h2>
<p>
Alle auf dieser Website verwendeten Bilder sind entweder urheberrechtsfrei oder wurden von den Eigent&uuml;mern f&uuml;r die Verwendung auf dieser Website freigegeben.
</p>
<p>
Gem&auml;&szlig; &sect; 5 Abs. 3 <acronym title="Teledienstegesetz">TDG</acronym> sind Anbieter von Websites f&uuml;r fremde Inhalte, zu denen sie lediglich den Zugang zur Nutzung vermitteln (z.B. durch Links), nicht verantwortlich.<br>
<font size="-2">
Landgericht Frankenthal (Pfalz) &ldquo;Keine Haftung f&uuml;r Links&rdquo; (Aktenzeichen 6 O 293/00)
</font>
</p>
<p>
Sollte sich dennoch jemand durch einen, auf dieser Website angebrachten, Link beeintr&auml;chtigt sehen oder im Falle einer unbeabsichtigten Urheberrechtsverletzung, bitten wir darum, den <a class="mailto" href="mailto:webmaster(at)hdlev.de?subject=bitte%20gib%20einen%20Betreff%20an%2C%20please%20type%20a%20subject&amp;body=Das%20%22%28at%29%22%20muss%20durch%20den%20Klammeraffen%20%22@%22%20ersetzt%20werden%0D%0A%0D%0A%22%28at%29%22%20must%20be%20replaced%20by%20%22@%22" title="Das (at) muss durch den Klammeraffen @ ersetzt werden!">Webmaster</a> zu benachrichtigen, damit der Link gepr&uuml;ft und ggf. entfernt werden kann bzw. die betreffende (Bild-)Datei umgehend entfernt wird.
</p>
  <h3>Nutzungsbedingungen</h3>
<h4>1. Inhalt des Onlineangebotes</h4>
<p>Die im Internet der Heidelberger Dart Liga e.V. (HDL) enthaltenen Inhalte k&ouml;nnen ohne vorherige Ank&uuml;ndigung erg&auml;nzt, ge&auml;ndert oder gel&ouml;scht werden. Wir behalten es uns ausdr&uuml;cklich vor, die Ver&ouml;ffentlichung zeitweise oder entg&uuml;ltig einzustellen. Alle Angebote sind freibleibend und unverbindlich.</p>
<h4>2. Verweise und Links</h4>
<p>Bei direkten oder indirekten Verweisen auf fremde Webseiten (&ldquo;Hyperlinks&rdquo;), die au&szlig;erhalb des Verantwortungsbereiches der HDL liegen, w&uuml;rde eine Haftungsverpflichtung ausschlie&szlig;lich in dem Fall in Kraft treten, in dem die HDL von den Inhalten Kenntnis hat und es ihr technisch m&ouml;glich und zumutbar w&auml;re, die Nutzung im Falle rechtswidriger Inhalte zu verhindern.</p>
<p>Die HDL erkl&auml;rt hiermit ausdr&uuml;cklich, dass zum Zeitpunkt der Linksetzung keine illegalen Inhalte auf den zu verlinkenden Seiten erkennbar waren. Auf die aktuelle und zuk&uuml;nftige Gestaltung, die Inhalte oder die Urheberschaft der gelinkten/verkn&uuml;pften Seiten hat die HDL keinerlei Einfluss. Deshalb distanziert sie sich hiermit ausdr&uuml;cklich von allen Inhalten aller gelinkten/verkn&uuml;pften Seiten, die nach der Linksetzung ver&auml;ndert wurden. Diese Feststellung gilt f&uuml;r alle innerhalb des eigenen Internetangebotes gesetzten Links und Verweise sowie f&uuml;r Fremdeintr&auml;ge in von der HDL eingerichteten G&auml;steb&uuml;chern, Diskussionsforen und Mailinglisten. F&uuml;r illegale, fehlerhafte oder unvollst&auml;ndige Inhalte und insbesondere f&uuml;r Sch&auml;den, die aus der Nutzung oder Nichtnutzung solcherart dargebotenen Informationen entstehen, haftet allein der Anbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der &uuml;ber Links auf die jeweilige Ver&ouml;ffentlichung lediglich verweist.</p>
<h4>3. Urheber- und Kennzeichenrecht</h4>
<p>Die HDL ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihr selbst erstellte Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zur&uuml;ckzugreifen.</p>
<p>Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte gesch&uuml;tzten Marken- und Warenzeichen unterliegen uneingeschr&auml;nkt den Bestimmungen des jeweils g&uuml;ltigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigent&uuml;mer. Allein aufgrund der blo&szlig;en Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter gesch&uuml;tzt sind.</p>
<p>Das Copyright f&uuml;r ver&ouml;ffentlichte, von der HDL selbst erstellte Objekte bleibt allein bei der HDL. Eine Vervielf&auml;ltigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdr&uuml;ckliche Zustimmung der HDL nicht gestattet.</p>
<p>Der Nutzer darf die Inhalte im Rahmen der angebotenen Funktionalit&auml;ten der Webseiten f&uuml;r seinen pers&ouml;nlichen Gebrauch nutzen. Im &uuml;brigen erwirbt er keine Rechte an den Inhalten und Programmen.</p>
<h4>4. Datenschutz</h4>
<p>Sofern innerhalb des Internetangebotes die M&ouml;glichkeit zur Eingabe pers&ouml;nlicher oder gesch&auml;ftlicher Daten (Emailadressen, Namen, Anschriften) besteht, so erfolgt die Preisgabe dieser Daten seitens des Nutzers auf ausdr&uuml;cklich freiwilliger Basis.</p>
<p>Wir erheben, verarbeiten und nutzen personenbezogene Daten des Nutzers nur insoweit, als dies zur Durchf&uuml;hrung der angebotenen Dienstleistungen erforderlich ist.</p>
<p>Wir leiten die Daten nicht an Dritte weiter, au&szlig;er dass dies zuvor dem Nutzer kenntlich gemacht und die &Uuml;bertragung vom Nutzer durch eine eindeutige und bewusste Handlung elektronisch ausgel&ouml;st worden ist.</p>
<p>Die Inanspruchnahme und Bezahlung aller angebotenen Dienste ist &ndash; soweit technisch m&ouml;glich und zumutbar &ndash; auch ohne Angabe solcher Daten bzw. unter Angabe anonymisierter Daten oder eines Pseudonyms gestattet. Die Nutzung der im Rahmen des Impressums oder vergleichbarer Angaben ver&ouml;ffentlichten Kontaktdaten wie Postanschriften, Telefon- und  Faxnummern sowie Emailadressen durch Dritte zur &Uuml;bersendung von nicht ausdr&uuml;cklich angeforderten Informationen ist nicht gestattet. Rechtliche Schritte gegen die Versender von sogenannten Spam-Mails bei Verst&ouml;&szlig;en gegen dieses Verbot sind ausdr&uuml;cklich vorbehalten.</p>
<h4>5. Haftungsausschluss</h4>
<p>Dieser Haftungsausschluss ist als Teil des Internetangebotes zu betrachten, von dem aus auf diese Seiten verwiesen wurde.</p>
<p>Die HDL &uuml;bernimmt keinerlei Gew&auml;hr f&uuml;r die Aktualit&auml;t, Korrektheit, Vollst&auml;ndigkeit oder Qualit&auml;t der bereitgestellten Informationen. Haftungsanspr&uuml;che gegen die HDL, welche sich auf Sch&auml;den materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollst&auml;ndiger Informationen verursacht wurden, sind grunds&auml;tzlich ausgeschlossen, sofern unsererseits kein nachweislich vors&auml;tzliches oder grob fahrl&auml;ssiges Verschulden vorliegt.</p>
<p>Die Haftung f&uuml;r Folgesch&auml;den und entgangenen Gewinn ist auch bei leichter Fahrl&auml;ssigkeit ausgeschlossen.</p>
<h4>6. Anwendbares Recht</h4>
<p>Das Verh&auml;ltnis der HDL zu ihren Nutzern unterliegt deutschem Recht.</p>
<h4>7. Salvatorische Klausel</h4>
<p>Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollst&auml;ndig entsprechen sollten, bleiben die &uuml;brigen Teile des Dokumentes in ihrem Inhalt und ihrer G&uuml;ltigkeit davon unber&uuml;hrt. Anstelle der unwirksamen Bestimmung gilt eine wirksame Bestimmung, die der gewollten am n&auml;chsten kommt. Gleiches gilt im Falle einer Regelungsl&uuml;cke.</p>